#!/usr/bin/python3

import sys
from math import exp, sqrt, pow, pi


def printHelp():
    print("USAGE")
    print("\t./205ducks u s [IQ1] [IQ2]\n\n")
    print("DESCRIPTION")
    print("\tu\tmean")
    print("\ts\tstandard deviation")
    print("\tIQ1\tminimum IQ")
    print("\tIQ2\tmaximum IQ")


def compute_density(u, s, x):
    result = (1 / (s * sqrt(2 * pi))) * exp(-(((x - u) ** 2) / (2 * s ** 2)))
    return (result)


def compute_density_in_range(u, s, min, max):
    for x in range(min, (max + 1)):
        print("{:d} {:.5f}".format(x, compute_density(u, s, x)))


def find_iq_inferior(u, s, IQ_min):
    total = 0.0
    x = 0.0

    while (x < IQ_min):
        total += compute_density(u, s, x)
        x += 0.01
    return (total)


def find_iq_between(u, s, IQ_min, IQ_max):
    total = 0.0
    x = IQ_min

    while (x < IQ_max):
        total += compute_density(u, s, x)
        x += 0.01
    return (total)


u = 0
s = 0
IQ_min = -1
IQ_max = -1
arg_len = len(sys.argv)

if (arg_len < 2 or arg_len > 5):
    printHelp()
    exit(84)

if (sys.argv[1] == "-h"):
    printHelp()
    exit(0)

try:
    u = float(sys.argv[1])
    s = float(sys.argv[2])
    if (arg_len > 3):
        IQ_min = int(sys.argv[3])
        if (IQ_min < 0 or IQ_min > 200):
            print("IQ must be between 0 and 200.")
            exit(84)
    if (arg_len > 4):
        IQ_max = int(sys.argv[4])
        if (IQ_max < 0 or IQ_max > 200):
            print("IQ must be between 0 and 200.")
            exit(84)
        if (IQ_min > IQ_max):
            exit(84)
    if (u < 0 or u > 200):
        exit(84)
    if (s <= 0 or s > 200):
        exit(84)
except ValueError:
    print("Error entry value please use ./205ducks u s [IQ1] [IQ2]")
    exit(84)
except:
    printHelp()
    exit(84)

if (IQ_min == -1 and IQ_max == -1):
    compute_density_in_range(u, s, 0, 200)
elif (IQ_min != -1 and IQ_max == -1):
    print("{:.1f}% of people have an IQ inferior to {:.0f}".format(find_iq_inferior(u, s, IQ_min), IQ_min))
elif (IQ_min != -1 and IQ_max != -1):
    print("{:.1f}% of people have an IQ between {:.0f} and {:.0f}".format(find_iq_between(u, s, IQ_min, IQ_max), IQ_min, IQ_max))